export default [
  {
    Bootcamp: "Tec de Monterrey",
    URL: "https://bootcamp.tec.mx/coding/es/",
    Programa: "Full Stack JS",
    País: "México",
    Estado: "",
    Costo: 5564,
    Beca: 8,
    Modalidad: "Tiempo parcial",
    Duración: "24 semanas",
    "En línea": "Sí",
    Comentarios: "Curso dictado en inglés.",
  },
  {
    Bootcamp: "Soy Henry",
    URL: "https://www.soyhenry.com/webfullstack",
    Programa: "Full Stack JS",
    País: "Internacional",
    Estado: "",
    Costo: 4000,
    Beca: null,
    Modalidad: "Tiempo completo",
    Duración: "16 semanas",
    "En línea": "Sí",
    Comentarios: "ISA (15%).",
  },
  {
    Bootcamp: "MUKTEK",
    URL: "https://www.muktek.com/cursos/js",
    Programa: "Full Stack JS",
    País: "México",
    Estado: "",
    Costo: 3890,
    Beca: null,
    Modalidad: "Tiempo completo",
    Duración: "28 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "MindHub",
    URL: "https://mindhubweb.com/bootcamps",
    Programa: "Full Stack JS | Java",
    País: "Internacional",
    Estado: "",
    Costo: 4400,
    Beca: null,
    Modalidad: "Tiempo completo",
    Duración: "16 semanas",
    "En línea": "Sí",
    Comentarios: "ISA opcional.",
  },
  {
    Bootcamp: "LoopGK",
    URL: "https://loopgk.com/bootcamp/",
    Programa: "Full Stack Python",
    País: "México",
    Estado: "Villahermosa",
    Costo: 120,
    Beca: 50,
    Modalidad: "",
    Duración: "11 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "Le Wagon",
    URL: "https://www.lewagon.com",
    Programa: "Desarrollo web",
    País: "Internacional",
    Estado: "",
    Costo: 5500,
    Beca: null,
    Modalidad: "Tiempo completo o parcial",
    Duración: "9 - 24 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "Laboratoria",
    URL: "https://www.laboratoria.la",
    Programa: "Full Stack JS",
    País: "Chile",
    Estado: "Santiago",
    Costo: 2111,
    Beca: null,
    Modalidad: "Tiempo completo",
    Duración: "24 semanas",
    "En línea": "Sí",
    Comentarios: "ISA (9%). Exclusivo mujeres.",
  },
  {
    Bootcamp: "Kodemia",
    URL: "https://kodemia.mx/javascript-live",
    Programa: "Full Stack JS",
    País: "México",
    Estado: "",
    Costo: 3700,
    Beca: 18,
    Modalidad: "Tiempo parcial",
    Duración: "22 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "KeepCoding",
    URL: "https://keepcoding.io/nuestros-bootcamps/full-stack-web-bootcamp/",
    Programa: "Full Stack JS",
    País: "Internacional",
    Estado: "",
    Costo: 6000,
    Beca: null,
    Modalidad: "Tiempo parcial",
    Duración: "32 semanas",
    "En línea": "Sí",
    Comentarios: "Descuento a residentes de LATAM.",
  },
  {
    Bootcamp: "Ironhack",
    URL: "https://www.ironhack.com/en/web-development/remote",
    Programa: "Full Stack JS",
    País: "Internacional",
    Estado: "",
    Costo: 5259,
    Beca: null,
    Modalidad: "Tiempo completo o parcial",
    Duración: "9 - 24 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "Generation",
    URL: "https://mexico.generation.org/cdmx-online/desarrolladora-java-full-stack/",
    Programa: "Full Stack Java",
    País: "México",
    Estado: "CDMX",
    Costo: 0,
    Beca: null,
    Modalidad: "Tiempo completo",
    Duración: "12 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "Egg",
    URL: "https://carreras.eggeducacion.com/ar/programacion/",
    Programa: "Full Stack Java",
    País: "Argentina",
    Estado: "",
    Costo: 955,
    Beca: 80,
    Modalidad: "Tiempo parcial",
    Duración: "36 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "Digital House",
    URL: "https://www.digitalhouse.com/ar/curso/programacion-web-full-stack",
    Programa: "Full Stack JS",
    País: "Argentina",
    Estado: "",
    Costo: 2236,
    Beca: 70,
    Modalidad: "Tiempo parcial",
    Duración: "26 semanas",
    "En línea": "Sí",
    Comentarios: "Becas del 70% en asociación con Becas Santander.",
  },
  // {
  //   Bootcamp: "Dev.F",
  //   URL: "https://www.devf.la",
  //   Programa: "Full Stack JS",
  //   País: "LATAM",
  //   Estado: "",
  //   Costo: null,
  //   Beca: null,
  //   Modalidad: "",
  //   Duración: "52 semanas",
  //   "En línea": "Sí",
  //   Comentarios: "",
  // },
  {
    Bootcamp: "Desafío LATAM",
    URL: "https://desafiolatam.com/full-stack-javascript-2022/",
    Programa: "Full Stack JS",
    País: "Chile",
    Estado: "",
    Costo: 2910,
    Beca: 60,
    Modalidad: "Tiempo parcial",
    Duración: "46 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "Coderhouse",
    URL: "https://www.coderhouse.com/online/carrera-online-desarrollo-fullstack",
    Programa: "Full Stack JS",
    País: "Argentina",
    Estado: "",
    Costo: 1363,
    Beca: 60,
    Modalidad: "Tiempo parcial",
    Duración: "49 semanas",
    "En línea": "Sí",
    Comentarios: "Se ofertan módulos individuales.",
  },
  {
    Bootcamp: "Codenotch",
    URL: "https://www.codenotch.com/bootcamp-de-desarrollo-web-y-movil/",
    Programa: "Full Stack web y móvil",
    País: "España",
    Estado: "Madrid",
    Costo: 7788,
    Beca: 24,
    Modalidad: "Tiempo completo",
    Duración: "12 semanas",
    "En línea": "Sí",
    Comentarios: "Becas para mujeres y desempleo.",
  },
  {
    Bootcamp: "Bright Coders",
    URL: "http://www.brightcoders.com",
    Programa: "Full Stack web | Móvil",
    País: "México",
    Estado: "Colima",
    Costo: 0,
    Beca: 100,
    Modalidad: "Tiempo parcial",
    Duración: "24 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
  {
    Bootcamp: "BEDU",
    URL: "https://bedu.org/lp/full-stack-javascript/",
    Programa: "Full Stack JS | Python",
    País: "México",
    Estado: "",
    Costo: 1580,
    Beca: null,
    Modalidad: "Tiempo parcial",
    Duración: "24 semanas",
    "En línea": "Sí",
    Comentarios: "Becas del 100% en asociación con Becas Santander.",
  },
  {
    Bootcamp: "4Geeks Academy",
    URL: "https://4geeksacademy.com/es/coding-bootcamps/full-stack-part-time",
    Programa: "Full Stack Python",
    País: "España",
    Estado: "Madrid",
    Costo: 3200,
    Beca: 20,
    Modalidad: "Tiempo completo y parcial",
    Duración: "16 semanas",
    "En línea": "Sí",
    Comentarios: "",
  },
];
